name: Lint Code Base
on:
  push:
    branches-ignore: [ main ]
jobs:
  linter-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint JavaScript
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linter-py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Python
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
